Metaswitch/homestead

debian/homestead.init.d
This allows `max_peers`, `num_http_threads`, `impu_cache_ttl` and `hss_reregistration_time` to be set in /etc/clearwater/config as well as /etc/clearwater/user_settings. user_settings takes priority, so there won't be a behaviour change unless one of those options is set in /etc/clearwater/config but not user_settings (and in that case the user probably *wants* that configuration option anyway).
`impu_cache_ttl` and `hss_reregistration_time` make much more sense in /etc/clearwater/config, because they affect Cassandra TTLs, and that's deployment-wide. `max_peers` also makes sense deployment-wide. `num_http_threads` maybe less so, but there's no harm in having the added flexibility.
Not tested - I propose to test by:
* setting hss_reregistration_time and max_peers to different values in …
=> Allow more settings to be in /etc/clearwater/config

src/main.cpp
Fixes https://github.com/Metaswitch/sprout/issues/973 (partly)
=> [Reviewer: Andy] Ensure process name passed to openlog() lasts for duration of program

debian/control
Ellie,
Please can you review this, which fixes #192.
I've tested live, and have similar changes to other components ready to go.
Matt
=> [Reviewer: Ellie] Homestead depends on libevent-2.0-5 and libcurl3-gnutls

homestead.root/usr/share/clearwater/infrastructure/scripts/homestead
Fixes #140. I'll test by doing a manual install with "public_hostnamme" set instead of "public_hostname" and check that the error is sensible.
=> [Reviewer: Ellie] Better errors when /etc/clearwater/config is missing settings

src/main.cpp, src/ut/realmmanager_test.cpp
This is the change we've discussed a couple of times now - to invoke RealmManager to manage the connections even if just a hss_hostname is specified, so the code is more consistent and predictable.
I'll test by setting up a HSS and configuring each of the three options:
* just hss_realm
* just hss_hostname
* both hss_realm and hss_hostname
and check that the CE/CEA exchage is successful in each case.
It's probably worth renaming RealmManager - how about DiameterConnectionManager?
=> [Reviewer: Matt] Pass the Diameter hostname to RealmManager along with the realm

debian/homestead.init.d
Fixes https://github.com/Metaswitch/homestead/issues/205. I've tested by running "pgrep -lf homestead" and checking that there was no "--diameter-timeout-ms=0" in the output.
=> [Reviewer: Andy] Don't use target_latency_us if it's unset

src/ut/handlers_test.cpp
The Jenkins memory leak errors were because I hadn't created a Diameter::Message and checked its properties in my new UT (to minimise the amount of things each test was asserting). Unfortunately, doing that also moves the contents of `_caught_fd_msg` onto the stack, so if we don't do that we leak memory.
This just creates (but doesn't use) a Diameter::Message to make sure that `_caught_fd_msg` is cleaned up properly.
=> [Reviewer: Matt] Fix memory leak in UT

homestead.root/usr/share/clearwater/clearwater-diags-monitor/scripts/homestead_diags
Graeme, please could you review this PR that fixes #195. 
To test this I:
* Set up deployments that used an external HSS (using an HSS realm and SRV records, and by configuring an HSS hostname directly). 
* Triggered a diags dump and checked that it contained the new diags.
* Broke the HSS connection (e.g. by configuring the wrong realml/hostname) and checked the diags dump showed what was wrong.
Once you have reviewed this I will make a similar change to Ralf.
=> Add more extra diags for homestead

homestead.root/usr/share/clearwater/infrastructure/scripts/homestead
We can't fail infrastructure scripts just because shared config hasn't arrived yet.  Tested live.
=> Reviewer Ellie - Don't fail infrastructure scripts

src/main.cpp
Adding in a extra log to explicitly show that Homestead quits when Cassandra is down
=> [Reviewer: Rob] Add in log explicitly saying Homestead is quitting

src/ut/cx_test.cpp, src/ut/diameterstack_test.cpp, src/ut/handlers_test.cpp
Stopped the unit tests from attempting to start a working diameter stack as this was causing test failures when the default port was already in use.
=> [Reviewer: Andy] Dont attempt to start the diameterstack for testing

debian/homestead.init.d
I've encountered HSSes that, when you send them an authentication scheme of "Unknown", send back weird things like "Early IMS Security".
This adds two new config options to counter that:
`hss_mar_force_digest=Y` - that AVP will always be 'SIP Digest'
`hss_mar_force_aka=Y` - that AVP will always be 'Digest-AKAv1-MD5'
To allow the quotes in "SIP Digest", I've used 'eval', as recommended by http://stackoverflow.com/questions/7454526/bash-variable-containing-multiple-args-with-quotes/21163341#21163341.
I've tested live by setting this config and checking the log at https://github.com/Metaswitch/homestead/blob/dev/src/main.cpp#L332.
=> [Reviewer: Andy] Allow configuring the Cx MAR authentication scheme more flexibly

debian/homestead.init.d
I've tested live, and confirmed:
* `ps aux | grep homestead` gives me the full command line (not cut off at the first semicolon)
* `sudo service homestead restart` doesn't give the error `/etc/init.d/homestead: 1: eval: --impu-cache-ttl=0: not found`
=> [Reviewer: Ellie] Add quotes around server_name to cope with semicolons

debian/control
Remove snmp-handler as Homestead uses the new style stats
=> [No reviewer] Remove snmp handler

homestead.root/usr/share/clearwater/infrastructure/scripts/homestead
Ellie,
Please can you review this fix to #269?  There'll be similar fixes coming to crest and memento shortly.  Basically, we just check that Cassandra is installed (which means it should be running) before we installed the schema.
Tested live.
Matt
=> [Reviewer: Ellie] Check that Cassandra is installed before installing schema

homestead.root/usr/share/clearwater/cassandra-schemas/homestead_cache.sh, src/ut/cache_test.cpp
Update UTs to handle TWO reads (from https://github.com/Metaswitch/cpp-common/pull/390), and update the schema to set the speculative retry value. 
If this is OK I'll make the same change to the other cassandra schemas, update the SAS bundle and add speculative_retry_value to the documentation
Part of the fix needed for #268
=> [Reviewer: Alex] Update UTs and schema

debian/homestead.init.d, src/main.cpp
Frequently (particularly in environments where DNS takes a long time to change - e.g. another team is managing the DNS server), I've wanted to be able to say "the HSS is reachable as IP address XXX, but the Destination-Host should be YYY, and the Destination-Realm should be ZZZ". (Currently, if you set hss_realm or hss_hostname, that gets resolved to find the peers, so there's no good way to uncouple the Diameter AVPs from the actual connection.)
This adds a config option to make that possible, so you can say:
```
force_hss_peer=XXX
hss_hostname=YYY
hss_realm=ZZZ
```
I haven't yet tested this live, but will do so.
=> [Reviewer: Ellie] Add force_hss_peer config option

src/ut/homestead_test.supp
This is the fix to the homestead UTs which complain (on some build systems) about an apparent memory leak in gnutls_init (as called by fd_core_initialize during DiameterStack startup).  
This is benign.  While the memory is indeed apparently leaked during the test, Homestead does not repeatedly start Diameter stacks outside of the UTs, so the leak can be ignored.
=> [Reviewer: Andy] Add known benign leak to homestead exceptions

debian/homestead.init.d
If a deployment has a value for hss_reregistration_time which is less than half of reg_max_expires, unexpected deregistration can occur (homestead might expire registrations before the clients EXPIRES timeout has elapsed).  
To minimise the chance of this happening, this PR defaults hss_registration_time to max (<the previous default - i.e. "1800">, $reg_max_expires / 2 ), thus allowing deployment administrators to configure arbitrary values for reg_max_expires without needing to explicitly configure hss_reregistration_time.
There are two related PRs (to be created shortly) in the following repositories
-  sprout.  A PR to add a comment to the code that defaults reg_max_expires that any changes to this value must be reflected in homestead.init.d
-  clearwater-docs. …
=> [Reviewer AMC] Default hss_reregistration_time based on reg_max_expires

include/handlers.h, src/Makefile, src/handlers.cpp, src/ut/handlers_test.cpp
Homestead part of https://github.com/Metaswitch/sprout/pull/1309.
Fixes https://github.com/Metaswitch/sprout/issues/1299
Also tested live. 
Please could you review?
Cheers,
Tom
=> [Reviewer Andy] Change autn header to be base64 encoded and rename

src/Makefile
Homestead (and some other projects) pass -lboost_date_time to the linker, but:
- this isn't actually used - I've confirmed that Homestead links without it
- https://github.com/Metaswitch/homestead/blob/dev/debian/control doesn't depend on libboost-date-time1.54.0, so if it was ever used, Homestead would fail to start
I'll apply the same change to our other Makefiles.
=> [Reviewer: Ellie] Don't link in unnecessary -lboost_date_time

homestead.root/usr/share/clearwater/infrastructure/scripts/homestead.monit
Use check-uptime to clear alarms and avoid suprious monit failures.
=> [Reviewer: None] Use updated check-uptime script.

homestead.root/usr/share/clearwater/infrastructure/scripts/check-homestead-uptime, homestead.root/usr/share/clearwater/infrastructure/scripts/homestead.monit
Monit can't pass arguments to check-program scripts in its current version.
=> [Reviewer: None] Cope with Monit restrictions

docs/homestead_api.md, include/handlers.h, src/handlers.cpp, src/ut/handlers_test.cpp
Allow Sprout to pass the server name through rather than always pulling it from the shared config
Fixes #66 (and is part of the fix for https://github.com/Metaswitch/sprout/issues/1405)
=> [Reviewer: Rob] Pass through the S-CSCF server name

src/Makefile, src/ut/homestead_test.supp
Steve,
Please can you review this fix to #324 (to suppress valgrind errors in gnutls when used from freeDiameter)?
Thanks,
Matt
=> [Reviewer: Steve] Apply valgrind suppression

include/handlers.h, src/handlers.cpp, src/ut/handlers_test.cpp
I think this fixes #345.
I should be able to repro the problem (and then test that it's fixed) by creating 2 GR sites through Chef and following the repro instructions in that issue.
=> [Reviewer: Matt] Tweak the Cassandra is_registered column so we heal better from netsplits

debian/homestead.init.d, homestead.root/usr/share/clearwater/bin/poll_homestead.sh
Same as https://github.com/Metaswitch/clearwater-infrastructure/pull/332, but for this repo.
=> Switch from Python version of bracket_ipv6_address to C++ version

include/handlers.h, src/handlers.cpp
Added tracing of Diameter returncodes to SAS.
Tested using an HSS that was rejecting deregistrations with a 5003 DIAMETER_AUTHORIZATION_REJECTED error
=> [Reviewer AJH]: SAS trace HSS returncodes

debian/homestead.init.d, src/main.cpp
Adds option to route SAS traffic via the signaling network
=> [Reviewer AJH] Allow SAS traffic to be optionally routed via signaling namespace

debian/homestead.init.d, include/handlers.h, src/handlers.cpp, src/main.cpp, src/ut/handlers_test.cpp
Fixes issue #360 as hss_reregistration_timeout can be configured to
0 to force all re-registrations to result in a SAR/SAA.
=> [Reviewer: RKD] Ensure records are preserved until binding expires

src/cache.cpp, src/handlers.cpp
***This PR is currently against the cached-data-api branch. If that branch has been merged by the time this gets merged, this should be merged into dev!***
Currently querying the list all IMPUs API doesn't return subscribers with unregistered service if you have an HSS configured because the reg state column doesn't exist. @rkd-msw thinks this is the right fix. I'm indifferent but it seems to work.
=> Reviewer AJH: Query subscription XML column for list all IMPUs

debian/control, homestead.root/usr/share/clearwater/infrastructure/scripts/create-homestead-nginx-config, include/cache.h, include/handlers.h, src/cache.cpp, src/handlers.cpp, src/main.cpp, src/ut/cache_test.cpp, src/ut/handlers_test.cpp, src/ut/mockcache.hpp
Hi Graeme, please can you review this change to add an HTTP management API to homestead to allow users to query a subscriber's IMS subscription, and to list all IMPUs homestead is storing data for.
I've tested this in UT, and also live using homestead prov:
* Try to get the subscription for a subscriber who doesn't exist. 
* Get the subscription of a subscriber that does exist. 
* List subscribers when none are configured. 
* List subscribers when some are configured. 
Graeme is doing a fuller live test.
=> [Reviewer: GDR] Add cached data management API. 

include/cache.h, src/handlers.cpp, src/ut/handlers_test.cpp, src/ut/mockcache.hpp
Adds some non-essential code as a follow-on from #375:
* Adds a unit test for one of the bugs found during live test. 
* Changes a function to return a const reference for safety.
=> [Reviewer: Graeme] Follow-ons from #375

src/main.cpp
Fixes #386 
Testing done:
- live tested (that not specifying a cassandra hostname uses 127.0.0.1)
- UTs and live tests pass
=> [Reviewer: Ellie] Use loopback IP rather than localhost for default cassandra hostname

src/handlers.cpp, src/ut/handlers_test.cpp
Consistently return a 503 when we hit an error on a request that can be retried.
Tested in UT
Fixes issue #389
=> [Reviewer: Seb] Make error codes consistent

homestead-cassandra.root/usr/share/clearwater/cassandra-schemas/homestead_cache.sh
We already print an error and exit if we can't poll cassandra within 2 minutes,
so this removes a benign but scary sounding log when you upgrade
Fixes #333 
**Testing done**
- tested that we no longer see the benign logs when upgrading
=> [Reviewer: Ellie] Suppress output of poll_cassandra when adding schemas

homestead-cassandra.root/usr/share/clearwater/cassandra-schemas/homestead_cache.sh
If the keyspace/table already exists, don't add it.
This removes the scary red logs from upgrade, and fixes #396 
**testing done**
- confirmed that the scary logs are removed
=> [Reviewer: Ellie] Don't create tables that already exist

include/homesteadsasevent.h, src/handlers.cpp
Fixes #308 
**Testing done**
- tested that an unsupported scheme (in this case `Early-IMS-Security`) triggered this debug log and SAS log
=> [Reviewer: Ellie] Add SAS log for unsupported auth scheme from HSS

src/handlers.cpp, src/ut/handlers_test.cpp
This means we treat a timeout as the same as having no diameter connections, and
allows the HTTP client to retry the request to another node if appropriate.
This is intended as a fix for https://github.com/Metaswitch/sprout/issues/1658
Testing done:
- manually verified that blocking HSS connections from one homestead now results in a 503 which is retried by the S-CSCF to another homestead node, resulting in the registration succeeding
- fixed UTs and verified they all pass
- the live tests pass
=> [Reviewer: Matt] Send HTTP 503 rather than 504 on diameter transaction timeout

include/cx.h, src/cx.cpp, src/handlers.cpp, src/ut/handlers_test.cpp
Homestead can now parse the "Wildcarded-Public-Id" AVP from the LIA, and pass it onto sprout over http.
I've modified HandlersTest.LocationInfoWithWildcard (written by EM) to test this works, and it passes.
All other homestead tests still pass.
=> Support wildcarded public ids on LIA

include/handlers.h, src/handlers.cpp, src/main.cpp, src/ut/handlers_test.cpp
**Change made**
I've removed the old deprecated ImpuIMSSubscriptionTask class (deprecated in 2014).
**Testing done**
I've removed three tests relating to this outdated code, as they are tested in the new code.
I edited a further three tests so that they cover the new class (ImpuRegDataTask).
I've checked that all tests run, including the live tests.
EM - I didn't rename any tests as they are already consistently named "IMSSubscription..."
=> Remove deprecated ImpuIMSSubscriptionTask

src/handlers.cpp
Removed some unnecessary info from one log:
- irrelevant result code
- constant experimental result code (instead just give this in the log)
Added some more info into another log, which will be logged when the wildcard is updated:
- old wildcard
- new wildcard
=> Update wildcard sas logs

src/handlers.cpp
Unescape the IMPU/IMPU as they could have encoded characters
Tested live.
=> [No reviewer] Unescape the params

include/cx.h, include/handlers.h, src/cx.cpp, src/handlers.cpp, src/ut/cx_test.cpp, src/ut/handlers_test.cpp
This PR takes the "sos=true" parameter on the UAR HTTP GET request from the I-CSCF and adds the UAR-Flags AVP on the Diameter UAR. Everything should be as in the design.
Sprout PR will follow shortly.
=> [Reviewer: KH1] Add support for the UAR-Flags AVP

debian/homestead.init.d, include/cx.h, include/handlers.h, src/cx.cpp, src/handlers.cpp, src/main.cpp, src/ut/cx_test.cpp
Adds support for a new config option to control setting the supported-features AVP for shared IFC sets
=> [Reviewer: Krista] Add config option to control shared IFC support

include/cache.h, include/handlers.h, include/homestead_xml_utils.h, include/homesteadsasevent.h, src/cache.cpp, src/handlers.cpp, src/homestead_xml_utils.cpp, src/ut/cache_test.cpp, src/ut/handlers_test.cpp, src/ut/mockcache.hpp
We can no longer guarantee that the default public id is the first public id in a registration set.
Instead, it is the first UNBARRED public id in a registration set.
Extra logic to pull out this updated definition of the default id has been added to the code that supports RTRs.
Several tests have been added to double check this works.
More tests need to be added in the future, before this code is added to V11, to handle the full range of RTRs that can be recieved.
=> Support barred IMPUs for RTRs

homestead-cassandra.root/usr/share/clearwater/cassandra-schemas/homestead_cache.sh
This is a fix for https://github.com/Metaswitch/clearwater-issues/issues/2152
The problem is that the poll_cassandra script now (correctly) polls the local cassandra process, where it used to poll the cassandra hostname. When creating a deployment in Chef, the DNS record isn't added until after the nodes are created.
Previously, this meant that the poll_cassandra script would block the schema addition until the DNS record existed, so that when the cqlsh command was run it could find the cassandra hostname.
With the change to the poll_cassandra script, it unblocks as soon as cassandra is running but before the DNS record exists. This means that the cqlsh command is unable to connect as the hostname can't be resolved.
The fix is just to connect to the local cassandra instance, since the …
=> [Reviewer: Ellie] Connect to local host when adding cassandra schemas

include/cache.h, src/cache.cpp, src/handlers.cpp, src/ut/cache_test.cpp, src/ut/handlers_test.cpp
There are 2 parts:
In split-storage, we retry to multiple cassandra nodes already, so we don't want Sprout to retry if there's an error.
I tested this by creating the error conditions manually, and making calls, verifying that we do indeed get 504 responses sent.
This is the corresponding change to https://github.com/Metaswitch/cpp-common/pull/649
Testing is described in that PR.
=> [Reviewer: Adam] Cassandra fixes

src/ut/cache_test.cpp
Added 2 UTs in my merge that missed the update that was previously made to the create_GetRegData()
This just fixes that in line with the previous changes in #445
=> [No reviewer] Fix UTs afer merge

homestead.root/usr/share/clearwater/infrastructure/scripts/homestead.monit
Following discussions with @eleanor-merry, we are going to clamp homestead's memory usage to 40% as it shares the node with Ralf on dime nodes.
=> [No reviewer] Clamp memory usage to 40%

src/cache.cpp
When there was only 1 private ID, debug logs said 
Looking for public IDs for private ID _____ and 1 others, implying there were 2 private IDs. It was counting that first ID twice. 
Changed it to "Looking for public IDs for private ID %s out of a total %d private IDs." to correct this.
=> Corrected some debug logs

include/cache.h, include/handlers.h, src/cache.cpp, src/cx.cpp, src/handlers.cpp, src/ut/cache_test.cpp, src/ut/handlers_test.cpp, src/ut/mockcache.hpp
PPR was failing to update the charging address when there was no IMS subscription element present. It should be able to update without this. Was previously failing to find any associated public IDs, since this function is only used when subscribers are locally provisioned. Changed such that it can correctly find the default IDs, then uses the Default ID to identify the Implicit Registration Set in order to update the charging address, rather than obtaining a list of all IDs. 
Tested for a simple subscription, with only one IMPI and one IMPU and it updates the charging information correctly. It also appears to update correctly with an IMPI and one implicit registration set, containing multiple IMPUs, although further testing is required.
=> PPR should update with only a charging address

debian/homestead.init.d, src/main.cpp
Follow on change from Metaswitch/cpp-common#664.
=> [No Reviewer] Use common code to calculate diameter timeout

include/handlers.h, include/sproutconnection.h, src/handlers.cpp, src/main.cpp, src/sproutconnection.cpp, src/ut/handlers_test.cpp, src/ut/mockhttpconnection.hpp
Upon receiving a PPR with a user-data element, Homestead will inform Sprout, via a HTTP PUT. It will send the XML, for Sprout to decode in order such that it can send any NOTIFYs about changed associated URIs.
If it receives a successful return code from sprout it will continue to update its store. 
If it receives a failure, it will send a failed PPA.  
This is unit tested and make full_test passes. 
This is live tested in the mainline case.
=> (Reviewer:Ellie) PPR Functionality to inform sprout

src/ut/cache_test.cpp
Follow on from Metaswitch/cpp-common#676
=> [No Reviewer] parse-ip-target moved to Utils

include/base_hss_cache.h, include/diameter_handlers.h, include/hss_cache.h, include/hss_cache_processor.h, include/http_handlers.h, include/memcached_cache.h, src/base_hss_cache.cpp, src/diameter_handlers.cpp, src/hss_cache_processor.cpp, src/http_handlers.cpp, src/memcached_cache.cpp, src/ut/diameter_handlers_test.cpp, src/ut/http_handlers_test.cpp, src/ut/memcachedcache_test.cpp, src/ut/mockhsscacheprocessor.hpp
Cache latency was too high when writing to remote sites because we were performing all the writes synchronously before returning a response to the request that caused us to perform a write.
This resolves that by allowing the `MemcachedCache` to write to the local site first, then call a progress callback (which tells the handler that it has succeeded in writing to the local site), and then continue to write to the remote sites once the handler has processed the local success.
This is done by:
* passing a `progress_callback` through the `HssCacheProcessor` to the `HssCache` for all put/delete operations
* changing the `BaseHssCache` to no longer treat a bulk delete as several deletes in a row (since it needs to perform the delete for all IRSs in the local site first, then call the progress …
=> [Reviewer: Richard] Improve cache latency

debian/control
`check_cx_health.py`, which is run by monit, requires that `python-netsnmp` is installed, as it imports netsnmp directly, without a virtual environment.
This commit adds an explicit Debian dependency on `python-netsnmp`.
=> [Reviewer: Seb] check_cx_health requires python-netsnmp

include/impu_store.h, src/impu_store.cpp
Seb,
This isn't very interesting, but adds a compression dictionary for the IMPU data.
Most of this is attempting to improve compression of the service profile data.
I've tested on some sample data that this improves our compression ratios.
=> [Reviewer: Seb] Add dictionary for IMPU caching

src/impu_store.cpp
Logging compressed bodies is pretty pointless, so this change stops us doing it.
The change is fairly simple because most of the change is in cpp-common - see https://github.com/Metaswitch/cpp-common/compare/sas_log_body
=> [Reviewer: Seb] Don't SAS log compressed bodies

include/charging_addresses.h, include/http_handlers.h, src/http_handlers.cpp
Also tidy up some unused variables, and fix cases where they were erroneously used
I've tested live that this SAS log appears correctly
=> [Reviewer: Richard] Reinstate the CACHE_PUT_REG_DATA sas log

homestead.root/usr/share/clearwater/infrastructure/scripts/homestead
Introduces a shared config option to set the delay between watchdog messages in freeDiameter, defaulting to 6s.
The script has undergone very basic live testing, with more to come.
=> [Reviewer: AJH] Add watchdog timer config option

debian/homestead.init.d
Adam,
Hopefully an uncontroversial change to allow homestead's HTTP threads to be configured independently.
I've tested setting `homestead_http_threads` on a Chef deployment and checking that they get picked up.
The equivalent of `sprout_worker_threads`, `homestead_cache_threads` is already standalone.
=> [Reviewer: Adam] Allow homestead_http_threads to be configured

include/memcached_cache.h, src/main.cpp, src/memcached_cache.cpp, src/ut/memcachedcache_test.cpp
If we fail to read data from the local site, read from all remote sites
simultaneously, and wait for them to return.
We do these reads on a thread pool dedicated to the Memcached Cache.
This means that if we have two sites, which both have a latency of 100ms, we'll only take 200ms to respond, rather than 400ms.
This makes us perform marginally worse in a net split scenario - if both sites have the data, the code will wait for both to return, rather than just asking the first site. If one of the sites has a much lower latency, this will make the performance slightly worse.
I've tested running Clearwater Live Test across a Chef deployment with three sites.
=> [Reviewer: Adam] Parallelize remote reads of IMPU data

include/impu_store.h, src/impu_store.cpp, src/memcached_cache.cpp, src/ut/memcachedcache_test.cpp
This is a fix for: https://github.com/Metaswitch/clearwater-issues/issues/2616
As discussed, this changes our writing to the cache so that we don't blind write data with reg-state UNREGISTERED to the cache.
I've put a fairly in-depth comment as to why we're doing this in the code.
I've added a UT for this race window, which fails before the fix and passes after. I've not attempted to replicate the race in live testing, as that didn't seem worth the effort.
At the moment we just ignore DATA_CONTENTION (writing a debug log, but nothing else). Does that sound sensible, or should we be SAS logging?
=> [Reviewer: Richard] Don't blind write UNREGISTERED data to the cache

debian/homestead.init.d
Default to 150 homestead cache threads per core, because cache operations are blocking.
I've live tested that this defaults correctly, and we've already live tested that this number of threads fixes the latency issues.
=> [Reviewer: Adam] 150 threads per core

include/impu_store.h, include/memcached_cache.h, src/impu_store.cpp, src/memcached_cache.cpp, src/ut/impu_store_test.cpp, src/ut/memcachedcache_test.cpp, src/ut/mockimpustore.hpp
This is a fix for: https://github.com/Metaswitch/clearwater-issues/issues/2627
There's an explanation in the issue as to what was happening, so not going to duplicate that here.
The fix is to allow `get_impi_mapping` to return a `Store::Status` (it now also takes an `ImpiMapping*` as an argument, which it sets if it succeeds).
This allows us to check why getting an ImpiMapping failed, because we want to treat NOT_FOUND differently from ERROR.
I've also added a MockImpuStore, as I needed it for the UTs I added.
`make full_test` passes.
As discussed, if this approach looks good, I'll make the corresponding change to the `get_impu_*` functions too, as those should really be treating ERROR and NOT_FOUND differently too.
=> [Reviewer: Richard] Check result of getting an ImpiMapping before using it

src/memcached_cache.cpp
We'll get memcached SAS logs here, so I'm not concerned about the lack of diagnostics in this case, and in the event of a GR site failure, it's just spam.
=> [Reviewer: Seb] Downgrade error log which is already SAS logged

include/base_hss_cache.h, include/diameter_hss_connection.h, include/hsprov_hss_connection.h, include/hss_cache.h, include/hss_cache_processor.h, include/hss_connection.h, include/memcached_cache.h, src/base_hss_cache.cpp, src/diameter_handlers.cpp, src/diameter_hss_connection.cpp, src/hsprov_hss_connection.cpp, src/hss_cache_processor.cpp, src/http_handlers.cpp, src/memcached_cache.cpp, src/ut/diameter_handlers_test.cpp, src/ut/diameter_hss_connection_test.cpp, src/ut/hsprov_hss_connection_test.cpp, src/ut/http_handlers_test.cpp, src/ut/memcachedcache_test.cpp, src/ut/mockhsscacheprocessor.hpp, src/ut/mockhssconnection.hpp, src/ut/mockimpustore.hpp
This PR adds the ability for Homestead to pause the StopWatch on an HTTPRequest when it's performing network I/O.
To achieve this, we've had to pass the StopWatch through the `HssCacheProcessor` and `HssConnection` interfaces.
The Diameter side already tracks Diameter latency, so we just subtract this from our total latency.
The memcached side doesn't, and threading complicates it further. We use the `IOHook`s in cpp-common to register hooks that the `MemcachedStore` will call into when it starts and stops network operations.
These hooks are stored in thread_local data, and are removed when they are deleted. So we must be careful to add the hook before doing any ImpuStore operations, and remove it after we're done.
We also need to be careful not to register any hooks after we've called …
=> [Reviewer: Richard] Don't track cache and HSS latency as part of our HTTP request latency

include/hss_cache_processor.h, src/Makefile, src/hss_cache_processor.cpp, src/main.cpp
_As discussed, we think we need this stat to help us diagnose issues, and it's a generally useful stat to track._
This PR adds a new stat to hometsead to track the size of the memcached thread pool's queue. It uses the same structure as the queue size that we track in Sprout.
`make full_test` passes, and I've live tested that we're reporting it correctly.
=> [Reviewer: Richard] Add memcached queue stats

homestead.root/usr/share/clearwater/bin/check_cx_health.py
The table lookup for timeouts may come back as not found for various reasons, e.g. when homestead process is killed. In such case, return a timeout value that's almost guaranteed to be higher than fault tolerance, as it's indicative that all connection attempts may have failed. 
Live tested by stopping homestead and running the script. It will have an error count of 400, and decides "All requests failing? True" if there isn't any successful connection at the same time.
=> Return large value for timeout if entry not found

src/ut/memcachedcache_test.cpp
Just add in a small real pause each time a mock call advances time to avoid some
double-counting of time spent by our stopwatch
We don't care that we may potentially be silghtly over-counting the latency, as we schedule some work and then immediately pause the stopwatch.
However, our UTs looks for a specific time, so they are stricter about this.
Sending to you as you reviewed originally. I think we should merge this into dev/master, but shout if you disagree
=> [Reviewer: Richard] Tweak to StopWatchGetImpuForImpuGR test

src/impu_store.cpp
Add parsed JSON data to SAS log for get/set of impi_mapping data.
This required removing the superfluous null character at the end of the JSON.  Checked with RJW2 and this is unnecessary.
=> [Reviewer: AJH] Add parsing of data to impi_mapping store

include/diameter_hss_connection.h, include/hsprov_hss_connection.h, include/http_handlers.h
As I mentioned on Friday, I spotted some subclasses that didn't have virtual destructors. Figured we should add them so that we don't get tripped up by them in the future. (I've checked that all the classes in `http_handlers.h` and `diameter_handlers.h` now have them.)
=> [Reviewer: Richard] Add some virtual destructors where they're missing

homestead.root/usr/share/clearwater/bin/check_cx_health
This is a fix for: https://github.com/Metaswitch/clearwater-issues/issues/3638
We must not `set -e`, because we want to intercept the non-zero exit code that the python script returns and then possibly ignore it.
I think that we do the checks this way round so that we can report that we're ignoring the error because the process is not yet stable, so the fix I've gone for is just to ensure that we don't `set -e` at the start.
I've had a look through the other scripts that use the `monit_stability` script, and none of the others use `set -e` so I think this is the complete fix.
I've tested that this works by:
1) On a node with the original script, replacing the python call in `check_cx_health` with a call to a function that just returns 3, and verifying that I see restarts within the 20s …
=> check_cx_health should wait for the process to be stable before reporting the error.

src/Makefile, src/main.cpp
Adds the ability to SIGHUP homestead to pick up new dns.json entries.
=> Load records from /etc/clearwater/dns.json

src/Makefile, src/main.cpp
Reverts Metaswitch/homestead#509
I thought we had tested this and it worked, but apparently not! Backing it out.
=> Revert "Load records from /etc/clearwater/dns.json"

src/diameter_handlers.cpp, src/http_handlers.cpp
Changed all instances of `add_compressed_param `to `add_var_param`
=> [Reviewer: CJR] Homestead - Disable Clientside SAS Compression

debian/homestead.init.d, homestead.root/usr/share/clearwater/infrastructure/scripts/reload/sas_json/homestead_reload, src/Makefile, src/main.cpp
This removes the reading/passing of the `sas_server` shared_config parameter from Homestead, instead using the new SasService module (associated PR: https://github.com/Metaswitch/cpp-common/pull/770)
=> [Reviewer: AJH] Integrate Homestead with the new sas.json file

docs/ManagementHttpAPI.md
Seb,
As part of the memcached work, we removed the API to list all subscribers which Homestead knows about, as that's not practical on memcached.
This corrects the docs in that area.
=> [Reviewer: Seb] Remove reference to retrieving all subscribers

src/diameter_hss_connection.cpp, src/http_handlers.cpp
As per https://github.com/Metaswitch/clearwater-issues/issues/3710, a bunch of extra logging added as part of the EC2 testing was accidentally left in. This PR just downgrades/removes those as they're per-call logs.
`make` and `make full_test` both pass.
=> [Reviewer: Adam] Fix logging
