debian/homestead.init.d
=> Fix config bugs

debian/homestead.init.d
Same change as https://github.com/Metaswitch/sprout/pull/808 but for Homestead. Not tested, but I'll start it up with debug logs on and verify that the arguments are recognised.
=> Move to --option=value format for command-line args

debian/homestead.init.d, src/main.cpp
Rob, can you review these changes to make the load monitor configurable. They're basically the same as https://github.com/Metaswitch/sprout/pull/944
=> [Reviewer: Rob] Make load monitor options configurable

debian/homestead.init.d, include/handlers.h, src/Makefile, src/handlers.cpp, src/main.cpp, src/ut/cache_test.cpp, src/ut/coverage-not-yet, src/ut/cx_test.cpp, src/ut/diameterstack_test.cpp, src/ut/handlers_test.cpp, src/ut/httpstack_test.cpp, src/ut/httpstack_utils_test.cpp
Rob, can you please review the Homestead changes for exception handling as well?
=> [Reviewer: Rob] Sto1117

debian/homestead.init.d, src/main.cpp
Should be pretty trivial: can you review this change to accept `signaling_dns_server=1.2.3.4,2.3.4.5`?
=> [Reviewer: Ellie] Multiple DNS servers

include/homesteadsasevent.h, src/handlers.cpp
The homestead equivalent of https://github.com/Metaswitch/sprout/pull/978
=> [Reviewer: Andy] Add new SAS events

homestead.root/usr/share/clearwater/bin/poll_homestead.sh, homestead.root/usr/share/clearwater/infrastructure/scripts/homestead.monit
Homestead changes (following template of https://github.com/Metaswitch/chronos/pull/107)
=> [Reviewer: Matt] Monit changes

include/cache.h, src/cache.cpp, src/main.cpp, src/ut/cache_test.cpp, src/ut/handlers_test.cpp, src/ut/mockcache.hpp
This PR contains some tweaks to the cache and it UTs to use the changes cassandra store infrastructure made under https://github.com/Metaswitch/cpp-common/pull/266. 
Tested by checking all the existing homestead UTs run.
=> [Reviewer: Rob] Co-req changes for sto1173

debian/homestead.init.d
Andy,
Please can you review my enhancement to add a `service ... run` option to run a service blocking (i.e. not as a daemon)?  Most of the changes are refactoring so that run and start can share the same code.
This has been tested live.
Thanks,
Matt
=> [Reviewer: Andy] Add service run command to run blocking

docs/homestead_api.md
Fixes up the example API calls
=> [No reviewer] Fix up JSON body

src/handlers.cpp, src/ut/handlers_test.cpp
Fixes https://github.com/Metaswitch/homestead/issues/210 (alongside https://github.com/Metaswitch/sprout/pull/1013).
=> [Reviewer: Ellie] ICSCF should send 480 when HSS sends 5003

debian/homestead.init.d, src/main.cpp
Same as https://github.com/Metaswitch/sprout/pull/1023.
=> [No review required] Make DNS blacklist duration configurable

debian/homestead.postinst, homestead.root/usr/share/clearwater/clearwater-cluster-manager/plugins/homestead_cassandra_plugin.py
This is the homestead equivalent of https://github.com/Metaswitch/crest/pull/200. Just in case you wanted to look at it...
=> Reviewer RKD: Add homestead cluster cassandra plugin

homestead.root/usr/share/clearwater/infrastructure/scripts/homestead.monit
Metaswitch/clearwater-monit#16
=> [No reviewer] Add in groups

debian/homestead.postinst, homestead.root/usr/share/clearwater/cassandra-schemas/homestead_cache.sh, homestead.root/usr/share/clearwater/clearwater-cluster-manager/plugins/homestead_cassandra_plugin.py, homestead.root/usr/share/clearwater/infrastructure/scripts/homestead.monit
=> [Reviewer: Rob] Cass 2.0.14

src/handlers.cpp, src/ut/handlers_test.cpp
Rob, can you review this fix to send back on 503 on local cassandra errors. 
Fixes #221 
Tested live
=> [Reviewer: Rob] Send 503 on local cassandra connection errors

homestead.root/usr/share/clearwater/clearwater-cluster-manager/plugins/homestead_cassandra_plugin.py
Co-req change to accompany Metaswitch/clearwater-etcd#70
=> [Reviewer: Andy] Enable cassandra clustering to cope with multiple networks

src/main.cpp
See https://github.com/Metaswitch/ralf/pull/160
=> Reviewer MIRW: Set default blacklist durations

src/cache.cpp, src/ut/cache_test.cpp
Hi Andy,
Could you also please review these changes. There are some UT and other changes caused by the interface change in [this PR](https://github.com/Metaswitch/cpp-common/pull/349).
Thanks,
Tom
=> [Reviewer: Andy] Fixed UT to test new quorum behaviour

debian/homestead.postinst, debian/homestead.prerm
Similar changes to https://github.com/Metaswitch/ralf/pull/174
=> [No reviewer] Minor fixes for the postinst/prerm files

homestead.root/usr/share/clearwater/cassandra-schemas/homestead_cache.sh
=> [Reviewer: Rob] Don't try to alter the table if the columns already exist

debian/homestead.postinst, homestead.root/usr/share/clearwater/infrastructure/scripts/homestead
Similar fix to https://github.com/Metaswitch/crest/pull/229
=> [No reviewer] Check config before running scripts

homestead.root/usr/share/clearwater/clearwater-cluster-manager/plugins/homestead_cassandra_plugin.py
Fix to remove spurious log (we may change this fix later when supporting stronger colocation). 
Fixes #243
=> [No reviewer] Check if homestead-prov is installed first

src/handlers.cpp, src/ut/handlers_test.cpp
=> [No review required] Implement Cx flows for non-registering PBXs

homestead.root/usr/share/clearwater/cassandra-schemas/homestead_cache.sh
Graeme, can you review this fix to use poll_cassandra in the schema creation scripts?
Tested live. This is the other part of the fix for https://github.com/Metaswitch/clearwater-cassandra/issues/54. If it's OK, I'll add this to the other schema creation scripts
=> [Reviewer: Graeme] Use poll_cass in schema creation script

src/ut/realmmanager_test.cpp
Associated UT changes for https://github.com/Metaswitch/cpp-common/pull/385.
=> Reviewer AMC: SRV priority and Diameter routing

src/ut/realmmanager_test.cpp
UTs https://github.com/Metaswitch/cpp-common/pull/396.
=> [Reviewer: Graeme] Add UT for negative SRV priorities

debian/homestead.init.d, src/main.cpp
Merging without review, same principle as Metaswitch/chronos#191.
=> [No reviewer] Implement a properly locked pidfile

homestead.root/usr/share/clearwater/cassandra-schemas/homestead_cache.sh
Hi Ellie,
This is Homestead part of Metaswitch/crest#264
Please could you review?
Thanks,
Tom
=> [Reviewer: Ellie] Run cqlsh in correct namespace

debian/homestead.init.d
=> [No reviewer] Create the pidfile directory even on 'make run'

src/ut/cache_test.cpp
Unit test for https://github.com/Metaswitch/cpp-common/pull/417
=> [Reviewer: Andy] Catch a thrift timeout exception and retry when doing a HA get

homestead.root/usr/share/clearwater/cassandra-schemas/homestead_cache.sh
Matching changes for https://github.com/Metaswitch/crest/pull/268
=> No reviewer: Create GR schema

debian/homestead.postinst, debian/homestead.triggers
Add alarm agent triggers - part of fix for https://github.com/Metaswitch/clearwater-snmp-handlers/issues/118
=> [No reviewer] Add alarm triggers

debian/homestead.init.d, debian/homestead.prerm
=> [No reviewer] Set PID ownership

homestead.root/usr/share/clearwater/infrastructure/scripts/homestead.monit
See clearwater-infrastructure for the new script which this uses.
=> [Reviewer Adam] Update homestead to use new uptime infrasturcture.

homestead.root/usr/share/clearwater/cassandra-schemas/homestead_cache.sh, include/authvector.h, src/cache.cpp, src/ut/cache_test.cpp
Rob,
Please can you review my tidy-up to remove the preferred flag.  As discussed in https://github.com/Metaswitch/homestead/issues/43, this flag isn't used.
I've run UT.
Matt
=> [Reviewer: Rob] Remove (unused) preferred flag from AV

homestead.root/usr/share/clearwater/cassandra-schemas/homestead_cache.sh, homestead.root/usr/share/clearwater/infrastructure/scripts/homestead
See https://github.com/Metaswitch/crest/pull/269.
=> [No reviewer] Bail out of schema scripts if Cassandra is not installed

debian/homestead.init.d
Dot in config file after setting defaults
=> [Reviewer: Graeme] Dot in config file after setting defaults

src/Makefile, src/main.cpp
Switch to a less congested logging facility for ENT logs
=> [Review AMC] Switch ENT logging channel to local7

debian/homestead.init.d
Homestead changes to match https://github.com/Metaswitch/sprout/pull/1364
=> [Reviewer: Rob] Config changes

src/Makefile
Uses https://github.com/Metaswitch/cpp-common/pull/511
=> Split signal handlers and utils

docs/homestead_api.md, include/handlers.h, src/handlers.cpp, src/ut/handlers_test.cpp
Moves the server name to the body
=> [Reviewer: Graeme] Move S-CSCF URI to body

src/main.cpp
Matching change to https://github.com/Metaswitch/sprout/pull/1444
=> [No reviewer] Always make an ENT log for bad SAS config

src/Makefile, src/main.cpp, src/ut/cache_test.cpp
Using the new AlarmManager from https://github.com/Metaswitch/cpp-common/pull/526
=> Use the new AlarmManager

debian/homestead.logrotate, src/main.cpp
This adds standard error / standard output logging to homestead.
=> [Reviewer: MIRW] Use common daemon setup/logging

src/main.cpp
=> [No reviewer] Use common daemon setup/logging

src/cx.cpp, src/ut/cx_test.cpp
**_DO NOT MERGE DURING CODE FREEZE_**
Fixes #362.
I've added a UT for the crash we were seeing, and verified that we did indeed crash. I then made the fix, and also renamed a bunch of other variables in cx.cpp. The UT now passes.
(I realise that there are probably various refactors we could be doing in areas of code I've changed in this PR, but I have no intention of doing those refactors)
=> Reviewer RKD: Fix crash if no SIP auth scheme on MAA

src/Makefile, src/main.cpp, src/ut/cache_test.cpp
Changes to homestead to use the new Cassandra connections
=> [Reviewer: Alex] Enhance Cassandra connections

debian/homestead.init.d, include/authvector.h, include/cx.h, include/handlers.h, src/cx.cpp, src/handlers.cpp, src/main.cpp, src/ut/handlers_test.cpp
I'll test live before merging.
=> [Reviewer: Ellie] Add Homestead-side changes for AKAv2 support

include/homestead_pd_definitions.h, src/Makefile, src/main.cpp
Friend of https://github.com/Metaswitch/cpp-common/pull/574
=> Reviewed: Use real syslog

docs/ManagementHttpAPI.md
This documents the API that was added by https://github.com/Metaswitch/homestead/pull/375.
=> Reviewer ???: Add documentation for the management HTTP API

homestead.root/usr/share/clearwater/infrastructure/scripts/homestead.monit
Use the correct issue-alarm call
=> [No reviewer] Update homestead.monit

src/handlers.cpp, src/ut/handlers_test.cpp
Updated UTs for the SARs/wildcards.
=> [Reviewer: Krista] Updated UT for SARs

src/handlers.cpp
This will probably end up containing several fixes. To start with, this fixes 2067.
=> [Reviewer: EM] Homestead diagnostics fixes

debian/homestead.init.d, src/main.cpp
Companion PR to https://github.com/Metaswitch/cpp-common/pull/641
=> [Reviewer EM] Plumb through DNS timeout

homestead.root/usr/share/clearwater/infrastructure/scripts/homestead.monit
As per https://github.com/Metaswitch/sprout/pull/1863
=> [No reviewer] Don't wait for 6 cycles before killing a process

debian/homestead.init.d, src/main.cpp
Change the default value of request_shared_ifcs to false.
I've not tested this yet, but I'll live test it before checking it in.
=> [Reviewer: Krista] Change default of request_shared_ifcs

include/handlers.h, src/handlers.cpp, src/ut/handlers_test.cpp
Alex, this PR passes through the provided server_name, if one exists, on the MAR to the HSS.
=> [Reviewer: AJH] Use provided server name on MAR

homestead-cassandra.root/usr/share/clearwater/cassandra-schemas/homestead_cache.sh
Equivalent changes to https://github.com/Metaswitch/crest/pull/356
=> [No reviewer] Update homestead_cache.sh

src/ut/diameter_handlers_test.cpp
Reinstate missing test lost in merge.
=> [No reviewer] Reinstate missing test

src/diameter_handlers.cpp, src/ut/diameter_handlers_test.cpp
[Reviewer AJH] Code with markups, rebuilt from scratch due to refactoring
=> Mark RTRs and PPRs as REGISTERs in SAS

src/ut/memcachedcache_test.cpp
Missing UT changes for https://github.com/Metaswitch/homestead/pull/486
=> [No reviewer] Fix up UTs

src/Makefile
OK, this should get it to the point it works. We'll need to merge the reload stuff later.
=> Doing enough to make it pass

src/Makefile, src/diameter_hss_connection.cpp, src/http_handlers.cpp, src/main.cpp
Changes from the apple scrumble branch with possibility into master
=> Extra Diags from the EANTC testing

homestead.root/etc/cron.hourly/homestead-log-cleanup
Can you review this one liner please? 
Testing: 
Create >2 files - check they're deleted
I'm not going to test the size limit works (since the only way to do that would be to make two files that were 750MB and it doesn't actually test much)
=> [Reviewer: RJW]Tidy up homestead logs

debian/control
`make deb` works.  Feel free to just merge in if you're happy
=> [Reviewer=RJW2] Add boost-thread dependency

debian/homestead.init.d, homestead.root/etc/cron.hourly/homestead-log-cleanup, src/main.cpp
Tweaked version of https://github.com/Metaswitch/homestead/pull/514
=> [No reviewer] Naive Ram Recorder

debian/homestead.init.d, src/main.cpp
See also https://github.com/Metaswitch/cpp-common/pull/773
=> Add support for RAM recording everything
